package com.kyroxova.continuumlib.knowledge.evidence;

public enum EvidenceType {
    EXACT_DESCRIPTOR_MATCH,
    SAME_OWNER,
    OWNER_MAPPING_MATCH,
    CLASS_MAPPING_MATCH,
    SAME_RETURN_TYPE,
    PARAMETER_SIMILARITY,
    BYTECODE_BODY_SIMILARITY,
    CALLSITE_SIMILARITY,
    MAPPING_FILE_RELATION,
    DEPRECATION_RELATION,
    DOCUMENTED_REPLACEMENT,
    MANUAL_VERIFICATION,
    TRANSFORMATION_TEST,
    TARGET_LINKAGE_TEST,
    RUNTIME_TEST,
    GAMEPLAY_TEST
}
