package com.kyroxova.continuumlib.model.diagnostic;

public enum DiagnosticCode {
    DUPLICATE_TARGET,
    BASE_REPEATED_AS_TARGET,
    NO_OUTPUT_MODE,
    UNRESOLVED_OPERATION,
    INVALID_TARGET_CONFIG,
    MALFORMED_FILTER_CONFIG,
    UNKNOWN_RULE_SCHEMA,
    DUPLICATE_RULE_ID,
    ARTIFACT_HASH_MISMATCH,
    INVALID_MAPPING_SETUP,
    AMBIGUOUS_MIGRATION,
    CONTRADICTORY_RULES,
    EXCLUDED_DECLARATION_REFERENCED,
    FAILED_COMPILATION,
    UNSAFE_OUTPUT_PATH,
    STRICT_TARGET_AUDIT_FAILURE,
    DUAL_CONFIGURATION_CONFLICT,
    MIGRATION_UNRESOLVED
}
